#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SQAddress
@end

@interface SQAddress : SQObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* firstName;

@property(nonatomic) NSString* lastName;

@property(nonatomic) NSString* jobTitle;

@property(nonatomic) NSString* telMobile;

@property(nonatomic) NSString* telDirect;

@property(nonatomic) NSString* linkedin;

@property(nonatomic) NSString* facebook;

@property(nonatomic) NSString* twitter;

@property(nonatomic) NSString* instagram;

@property(nonatomic) NSString* googleplus;

@property(nonatomic) NSNumber* user;

@end
