#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SQAddress.h"
#import "SQResponse.h"
#import "SQResponseLinks.h"


@protocol SQAddressResponseSingle
@end

@interface SQAddressResponseSingle : SQResponse


@property(nonatomic) SQAddress* data;

@property(nonatomic) SQResponseLinks* links;

@end
