#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SQError
@end

@interface SQError : SQObject


@property(nonatomic) NSNumber* code;

@property(nonatomic) NSString* detail;

@end
