#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SQFileObject.h"
#import "SQResponse.h"
#import "SQResponseLinks.h"


@protocol SQFileResponseMultiple
@end

@interface SQFileResponseMultiple : SQResponse


@property(nonatomic) NSArray<SQFileObject>* data;

@property(nonatomic) SQResponseLinks* links;

@end
