#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SQResponse.h"
#import "SQGlobalTemplate.h"


@protocol SQGlobalTemplateResponseMultiple
@end

@interface SQGlobalTemplateResponseMultiple : SQResponse


@property(nonatomic) NSArray<SQGlobalTemplate>* data;

@end
