#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SQJSONWebToken.h"


@protocol SQJSONWebTokenResponse
@end

@interface SQJSONWebTokenResponse : SQObject


@property(nonatomic) SQJSONWebToken* data;

@end
