#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SQLinks
@end

@interface SQLinks : SQObject


@property(nonatomic) NSString* self;

@property(nonatomic) NSString* related;

@property(nonatomic) NSString* next;

@property(nonatomic) NSString* last;

@end
