#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SQLoginDetails
@end

@interface SQLoginDetails : SQObject


@property(nonatomic) NSString* username;

@property(nonatomic) NSString* password;

@end
