#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SQResponseLinks.h"


@protocol SQResponse
@end

@interface SQResponse : SQObject


@property(nonatomic) SQResponseLinks* links;

@end
