#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SQResponse.h"
#import "SQSignature.h"


@protocol SQSignatureResponseSingle
@end

@interface SQSignatureResponseSingle : SQResponse


@property(nonatomic) SQSignature* data;

@end
