#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SQSignature
@end

@interface SQSignature : SQObject


@property(nonatomic) NSString* plain;

@property(nonatomic) NSString* rich;

@property(nonatomic) NSString* html;

@end
