#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SQSnippet
@end

@interface SQSnippet : SQObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* contentHtml;

@property(nonatomic) NSString* contentPlaintext;

@property(nonatomic) NSString* contentRichtext;

@property(nonatomic) NSString* thumbnail;

@property(nonatomic) NSNumber* user;

@end
