#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SQResponse.h"
#import "SQResponseLinks.h"
#import "SQTemplate.h"


@protocol SQTemplateResponseMultiple
@end

@interface SQTemplateResponseMultiple : SQResponse


@property(nonatomic) NSArray<SQTemplate>* data;

@property(nonatomic) SQResponseLinks* links;

@end
