#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SQTemplate.h"
#import "SQResponse.h"


@protocol SQTemplateResponseSingle
@end

@interface SQTemplateResponseSingle : SQResponse


@property(nonatomic) SQTemplate* data;

@end
