#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SQTemplate
@end

@interface SQTemplate : SQObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSNumber* user;

@property(nonatomic) NSNumber* globalTemplate;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSString* contentHtml;

@property(nonatomic) NSString* contentPlaintext;

@property(nonatomic) NSNumber* thumbnail;

@property(nonatomic) NSString* settings;

@property(nonatomic) NSDate* createdAt;

@property(nonatomic) NSDate* updatedAt;

@end
