#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SQUnexpectedErrorResponse
@end

@interface SQUnexpectedErrorResponse : SQObject


@property(nonatomic) NSArray* /* NSObject */ errors;

@end
