#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SQResponse.h"
#import "SQUser.h"


@protocol SQUserResponseSingle
@end

@interface SQUserResponseSingle : SQResponse


@property(nonatomic) SQUser* data;

@end
