#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SQUser
@end

@interface SQUser : SQObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* companyName;

@property(nonatomic) NSString* firstName;

@property(nonatomic) NSString* lastName;

@property(nonatomic) NSString* domain;

@property(nonatomic) NSString* address1;

@property(nonatomic) NSString* address2;

@property(nonatomic) NSString* address3;

@property(nonatomic) NSString* addressCity;

@property(nonatomic) NSString* addressPostcode;

@property(nonatomic) NSString* addressCountry;

@property(nonatomic) NSString* website;

@property(nonatomic) NSString* tel;

@property(nonatomic) NSString* linkedin;

@property(nonatomic) NSString* facebook;

@property(nonatomic) NSString* twitter;

@property(nonatomic) NSString* instagram;

@property(nonatomic) NSString* googleplus;

@property(nonatomic) NSNumber* snippet;

@end
