#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SQResponse.h"
#import "SQResponseLinks.h"
#import "SQUser.h"


@protocol SQUserResponseMultiple
@end

@interface SQUserResponseMultiple : SQResponse


@property(nonatomic) NSArray<SQUser>* data;

@property(nonatomic) SQResponseLinks* links;

@end
