#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Squiggle API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQSignature.h"


@protocol SQAddress
@end

@interface SQAddress : SQObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* password;

@property(nonatomic) NSString* firstName;

@property(nonatomic) NSString* lastName;

@property(nonatomic) NSString* jobTitle;

@property(nonatomic) NSString* telMobile;

@property(nonatomic) NSString* telDirect;

@property(nonatomic) NSString* linkedin;

@property(nonatomic) NSString* facebook;

@property(nonatomic) NSString* twitter;

@property(nonatomic) NSString* instagram;

@property(nonatomic) NSString* googleplus;

@property(nonatomic) NSNumber* template;

@property(nonatomic) NSArray<SQSignature>* signatures;

@property(nonatomic) NSDate* createdAt;

@property(nonatomic) NSDate* updatedAt;

@end
