#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Squiggle API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SQClient
@end

@interface SQClient : SQObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* version;

@property(nonatomic) NSString* osName;

@property(nonatomic) NSString* pluginVersion;

@property(nonatomic) NSDate* lastCheckin;

@property(nonatomic) NSDate* createdAt;

@end
