#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Squiggle API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SQResponseLinks
@end

@interface SQResponseLinks : SQObject


@property(nonatomic) NSString* self;

@property(nonatomic) NSString* related;

@property(nonatomic) NSString* next;

@property(nonatomic) NSString* last;

@end
