#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Squiggle API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQTemplate.h"


@protocol SQSignature
@end

@interface SQSignature : SQObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* label;

@property(nonatomic) SQTemplate* template;

@property(nonatomic) NSString* plain;

@property(nonatomic) NSString* html;

@property(nonatomic) NSDictionary<NSString*, NSString*>* errors;

@end
