#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Squiggle API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQFileTemplate.h"


@protocol SQUserTemplate
@end

@interface SQUserTemplate : SQObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* companyName;

@property(nonatomic) NSString* firstName;

@property(nonatomic) NSString* lastName;

@property(nonatomic) NSString* domain;

@property(nonatomic) NSString* address1;

@property(nonatomic) NSString* address2;

@property(nonatomic) NSString* address3;

@property(nonatomic) NSString* addressCity;

@property(nonatomic) NSString* addressPostcode;

@property(nonatomic) NSString* addressCountry;

@property(nonatomic) NSString* tel;

@property(nonatomic) NSString* website;

@property(nonatomic) NSString* linkedin;

@property(nonatomic) NSString* facebook;

@property(nonatomic) NSString* twitter;

@property(nonatomic) NSString* instagram;

@property(nonatomic) NSString* googleplus;

@property(nonatomic) NSString* additionalText;

@property(nonatomic) SQFileTemplate* logo;

@end
