#import <Foundation/Foundation.h>
#import "SQAddress.h"
#import "SQFileObject.h"
#import "SQGlobalTemplate.h"
#import "SQJSONWebTokenResponse.h"
#import "SQLoginDetails.h"
#import "SQSnippet.h"
#import "SQTemplate.h"
#import "SQUnexpectedErrorResponse.h"
#import "SQUser.h"
#import "SQApi.h"

/**
* Squiggle API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SQDefaultApi: NSObject <SQApi>

extern NSString* kSQDefaultApiErrorDomain;
extern NSInteger kSQDefaultApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// 
/// Creates a new address
///
/// @param data 
/// 
///  code:201 message:"Address created successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQAddress*
-(NSNumber*) addAddressWithData: (SQAddress*) data
    completionHandler: (void (^)(SQAddress* output, NSError* error)) handler;


/// 
/// Upload a new file
///
/// @param file 
/// @param name  (optional)
/// 
///  code:201 message:"File uploaded successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQFileObject*
-(NSNumber*) addFileWithFile: (NSURL*) file
    name: (NSString*) name
    completionHandler: (void (^)(SQFileObject* output, NSError* error)) handler;


/// 
/// Creates a new global template
///
/// @param data 
/// 
///  code:201 message:"Global template created successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQGlobalTemplate*
-(NSNumber*) addGlobalTemplateWithData: (SQGlobalTemplate*) data
    completionHandler: (void (^)(SQGlobalTemplate* output, NSError* error)) handler;


/// 
/// Creates a new snippet
///
/// @param data 
/// 
///  code:201 message:"Snippet created successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQSnippet*
-(NSNumber*) addSnippetWithData: (SQSnippet*) data
    completionHandler: (void (^)(SQSnippet* output, NSError* error)) handler;


/// 
/// Creates a new template
///
/// @param data 
/// 
///  code:201 message:"Template created successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQTemplate*
-(NSNumber*) addTemplateWithData: (SQTemplate*) data
    completionHandler: (void (^)(SQTemplate* output, NSError* error)) handler;


/// 
/// Creates a new user
///
/// @param data 
/// 
///  code:201 message:"User created successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQUser*
-(NSNumber*) addUserWithData: (SQUser*) data
    completionHandler: (void (^)(SQUser* output, NSError* error)) handler;


/// 
/// Deletes an address with the specified ID
///
/// @param _id ID of address to delete
/// 
///  code:204 message:"Address deleted successfully",
///  code:0 message:"Unexpected Error"
///
/// @return 
-(NSNumber*) deleteAddressWithId: (NSNumber*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// Deletes a file with the specified ID
///
/// @param _id ID of file to delete
/// 
///  code:204 message:"File deleted successfully",
///  code:0 message:"Unexpected Error"
///
/// @return 
-(NSNumber*) deleteFileWithId: (NSNumber*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// Deletes a global template with the specified ID
///
/// @param _id ID of global template to delete
/// 
///  code:204 message:"Global template deleted successfully",
///  code:0 message:"Unexpected Error"
///
/// @return 
-(NSNumber*) deleteGlobalTemplateWithId: (NSNumber*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// Deletes a snippet with the specified ID
///
/// @param _id ID of snippet to delete
/// 
///  code:204 message:"Snippet deleted successfully",
///  code:0 message:"Unexpected Error"
///
/// @return 
-(NSNumber*) deleteSnippetWithId: (NSNumber*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// Deletes a template with the specified ID
///
/// @param _id ID of template to delete
/// 
///  code:204 message:"Template deleted successfully",
///  code:0 message:"Unexpected Error"
///
/// @return 
-(NSNumber*) deleteTemplateWithId: (NSNumber*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// Deletes a user with the specified ID
///
/// @param _id ID of user to delete
/// 
///  code:204 message:"User deleted successfully",
///  code:0 message:"Unexpected Error"
///
/// @return 
-(NSNumber*) deleteUserWithId: (NSNumber*) _id
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// Updates an existing address with the specified ID
///
/// @param _id ID of address to update
/// @param data 
/// 
///  code:200 message:"Address updated successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQAddress*
-(NSNumber*) editAddressWithId: (NSNumber*) _id
    data: (SQAddress*) data
    completionHandler: (void (^)(SQAddress* output, NSError* error)) handler;


/// 
/// Updates an existing file with the specified ID
///
/// @param _id ID of file to update
/// @param file  (optional)
/// @param name  (optional)
/// 
///  code:200 message:"File updated successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQFileObject*
-(NSNumber*) editFileWithId: (NSNumber*) _id
    file: (NSURL*) file
    name: (NSString*) name
    completionHandler: (void (^)(SQFileObject* output, NSError* error)) handler;


/// 
/// Updates an existing global template with the specified ID
///
/// @param _id ID of global template to update
/// @param data 
/// 
///  code:200 message:"Global template updated successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQGlobalTemplate*
-(NSNumber*) editGlobalTemplateWithId: (NSNumber*) _id
    data: (SQGlobalTemplate*) data
    completionHandler: (void (^)(SQGlobalTemplate* output, NSError* error)) handler;


/// 
/// Updates an existing snippet with the specified ID
///
/// @param _id ID of snippet to update
/// @param data 
/// 
///  code:200 message:"Snippet updated successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQSnippet*
-(NSNumber*) editSnippetWithId: (NSNumber*) _id
    data: (SQSnippet*) data
    completionHandler: (void (^)(SQSnippet* output, NSError* error)) handler;


/// 
/// Updates an existing template with the specified ID
///
/// @param _id ID of template to update
/// @param data 
/// 
///  code:200 message:"Template updated successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQTemplate*
-(NSNumber*) editTemplateWithId: (NSNumber*) _id
    data: (SQTemplate*) data
    completionHandler: (void (^)(SQTemplate* output, NSError* error)) handler;


/// 
/// Updates an existing user with the specified ID
///
/// @param _id ID of user to update
/// @param data 
/// 
///  code:200 message:"User updated successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQUser*
-(NSNumber*) editUserWithId: (NSNumber*) _id
    data: (SQUser*) data
    completionHandler: (void (^)(SQUser* output, NSError* error)) handler;


/// 
/// Gets addresses
///
/// @param offset The start offset of the result set (optional)
/// @param limit Max records to return (optional)
/// 
///  code:200 message:"Successful response",
///  code:0 message:"Unexpected Error"
///
/// @return NSArray<SQAddress>*
-(NSNumber*) findAddressesWithOffset: (NSNumber*) offset
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<SQAddress>* output, NSError* error)) handler;


/// 
/// Gets files
///
/// @param offset The start offset of the result set (optional)
/// @param limit Max records to return (optional)
/// 
///  code:200 message:"Successful response",
///  code:0 message:"Unexpected Error"
///
/// @return NSArray<SQFileObject>*
-(NSNumber*) findFilesWithOffset: (NSNumber*) offset
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<SQFileObject>* output, NSError* error)) handler;


/// 
/// Gets global templates
///
/// @param offset The start offset of the result set (optional)
/// @param limit Max records to return (optional)
/// 
///  code:200 message:"Successful response",
///  code:0 message:"Unexpected Error"
///
/// @return NSArray<SQGlobalTemplate>*
-(NSNumber*) findGlobalTemplatesWithOffset: (NSNumber*) offset
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<SQGlobalTemplate>* output, NSError* error)) handler;


/// 
/// Gets snippets
///
/// @param offset The start offset of the result set (optional)
/// @param limit Max records to return (optional)
/// 
///  code:200 message:"Successful response",
///  code:0 message:"Unexpected Error"
///
/// @return NSArray<SQSnippet>*
-(NSNumber*) findSnippetsWithOffset: (NSNumber*) offset
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<SQSnippet>* output, NSError* error)) handler;


/// 
/// Gets templates
///
/// @param offset The start offset of the result set (optional)
/// @param limit Max records to return (optional)
/// 
///  code:200 message:"Successful response",
///  code:0 message:"Unexpected Error"
///
/// @return NSArray<SQTemplate>*
-(NSNumber*) findTemplatesWithOffset: (NSNumber*) offset
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<SQTemplate>* output, NSError* error)) handler;


/// 
/// Gets users
///
/// @param offset The start offset of the result set (optional)
/// @param limit Max records to return (optional)
/// 
///  code:200 message:"Successful response",
///  code:0 message:"Unexpected Error"
///
/// @return NSArray<SQUser>*
-(NSNumber*) findUsersWithOffset: (NSNumber*) offset
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<SQUser>* output, NSError* error)) handler;


/// 
/// Gets an address with the specified ID
///
/// @param _id ID of address to get
/// 
///  code:200 message:"Successful response",
///  code:0 message:"Unexpected Error"
///
/// @return SQAddress*
-(NSNumber*) getAddressWithId: (NSNumber*) _id
    completionHandler: (void (^)(SQAddress* output, NSError* error)) handler;


/// 
/// Request JWT for Address
///
/// @param data 
/// 
///  code:200 message:"Token Created Successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQJSONWebTokenResponse*
-(NSNumber*) getAddressTokenWithData: (SQLoginDetails*) data
    completionHandler: (void (^)(SQJSONWebTokenResponse* output, NSError* error)) handler;


/// 
/// Gets a file with the specified ID
///
/// @param _id ID of file to get
/// 
///  code:200 message:"Successful response",
///  code:0 message:"Unexpected Error"
///
/// @return SQFileObject*
-(NSNumber*) getFileWithId: (NSNumber*) _id
    completionHandler: (void (^)(SQFileObject* output, NSError* error)) handler;


/// 
/// Gets a global template with the specified ID
///
/// @param _id ID of global template to get
/// 
///  code:200 message:"Successful response",
///  code:0 message:"Unexpected Error"
///
/// @return SQGlobalTemplate*
-(NSNumber*) getGlobalTemplateWithId: (NSNumber*) _id
    completionHandler: (void (^)(SQGlobalTemplate* output, NSError* error)) handler;


/// 
/// Gets a snippet with the specified ID
///
/// @param _id ID of snippet to get
/// 
///  code:200 message:"Successful response",
///  code:0 message:"Unexpected Error"
///
/// @return SQSnippet*
-(NSNumber*) getSnippetWithId: (NSNumber*) _id
    completionHandler: (void (^)(SQSnippet* output, NSError* error)) handler;


/// 
/// Gets a template with the specified ID
///
/// @param _id ID of template to get
/// 
///  code:200 message:"Successful response",
///  code:0 message:"Unexpected Error"
///
/// @return SQTemplate*
-(NSNumber*) getTemplateWithId: (NSNumber*) _id
    completionHandler: (void (^)(SQTemplate* output, NSError* error)) handler;


/// 
/// Gets a user with the specified ID
///
/// @param _id ID of user to get
/// 
///  code:200 message:"Successful response",
///  code:0 message:"Unexpected Error"
///
/// @return SQUser*
-(NSNumber*) getUserWithId: (NSNumber*) _id
    completionHandler: (void (^)(SQUser* output, NSError* error)) handler;


/// 
/// Request JWT for User
///
/// @param data 
/// 
///  code:200 message:"Token Created Successfully",
///  code:0 message:"Unexpected Error"
///
/// @return SQJSONWebTokenResponse*
-(NSNumber*) getUserTokenWithData: (SQLoginDetails*) data
    completionHandler: (void (^)(SQJSONWebTokenResponse* output, NSError* error)) handler;



@end
